import sys, json, os, glob, re, time
import google.generativeai as genai
from dotenv import load_dotenv

sys.stdout.reconfigure(encoding='utf-8')
load_dotenv()
gemini_keys = os.getenv("GEMINI_API_KEYS", "").split(",")
genai.configure(api_key=gemini_keys[0].strip())
model = genai.GenerativeModel('gemini-3.1-flash-lite-preview')

# =====================================================================
# Bước 1: Trích xuất nội dung text thuần từ JSON giáo trình (Proposed)
# =====================================================================
def extract_text_from_json(filepath):
    """Trích text thuần từ JSON giáo trình (bỏ HTML tags)"""
    d = json.load(open(filepath, 'r', encoding='utf-8'))
    topic = d.get('topic', '?')
    book = d.get('book_vi') or d.get('ui_book') or {}
    chapters = book.get('chapters') or []
    
    lines = [f"Giáo trình: {topic}\n"]
    
    for ch in chapters:
        ch_title = ch.get('title', '')
        lines.append(f"\n## {ch_title}")
        sections = ch.get('sections') or []
        for sec in sections:
            sec_title = sec.get('title', '')
            content = sec.get('content', '')
            # Bỏ HTML tags
            clean = re.sub(r'<[^>]+>', '', content)
            clean = re.sub(r'\s+', ' ', clean).strip()
            lines.append(f"\n### {sec_title}")
            lines.append(clean[:1500])  # Giới hạn mỗi section 1500 chars
    
    full_text = "\n".join(lines)
    return topic, full_text

# =====================================================================
# Bước 2: Chọn best curriculum cho mỗi chủ đề (file lớn nhất = nhiều nội dung nhất)
# =====================================================================
json_dir = r'd:\tu_dong_giao_trinh\du_lieu\dau_ra\json'
all_files = glob.glob(os.path.join(json_dir, '*.json'))

# Group by topic, pick largest file per topic
topic_best = {}
for f in all_files:
    try:
        d = json.load(open(f, 'r', encoding='utf-8'))
        topic = d.get('topic', '?')
        sz = os.path.getsize(f)
        if topic not in topic_best or sz > topic_best[topic][1]:
            topic_best[topic] = (f, sz)
    except:
        pass

print(f"Found {len(topic_best)} unique topics:")
for t, (f, sz) in sorted(topic_best.items(), key=lambda x: -x[1][1]):
    print(f"  {t}: {os.path.basename(f)} ({sz:,} bytes)")

# =====================================================================
# Bước 3: LLM-as-a-Judge chấm điểm RAGAS 5 tiêu chí
# =====================================================================
eval_prompt = """You are an expert evaluator for AI-generated educational textbooks.
You are evaluating a university-level textbook on "{topic}" generated by a multi-agent RAG system.

Score from 0.0 to 1.0 for each metric:
1. Context Relevance: Is the content focused on the topic? Are all sections directly relevant? Penalize if off-topic or filler content.
2. Faithfulness: Is the factual content accurate? Are citations present? Penalize fabricated facts.
3. Answer Correctness: Is the curriculum structure appropriate and comprehensive for a university course?
4. Coherence: Is the logical flow from basic to advanced well-structured? Are chapters coherent?
5. Consistency: Is the depth, terminology, and academic tone consistent throughout?

TEXTBOOK CONTENT (truncated):
{text}

Return ONLY in this exact format:
Context Relevance: X.XX
Faithfulness: X.XX
Answer Correctness: X.XX
Coherence: X.XX
Consistency: X.XX"""

results = []
for topic, (fpath, sz) in sorted(topic_best.items(), key=lambda x: -x[1][1])[:10]:
    try:
        topic_name, text = extract_text_from_json(fpath)
        # Truncate to ~6000 chars for LLM
        text_truncated = text[:6000]
        
        prompt = eval_prompt.format(topic=topic_name, text=text_truncated)
        
        retries = 3
        while retries > 0:
            try:
                response = model.generate_content(prompt, generation_config=genai.types.GenerationConfig(temperature=0.0))
                reply = response.text
                
                cr = float(re.search(r'Context Relevance:\s*([\d\.]+)', reply).group(1))
                fa = float(re.search(r'Faithfulness:\s*([\d\.]+)', reply).group(1))
                ac = float(re.search(r'Answer Correctness:\s*([\d\.]+)', reply).group(1))
                co = float(re.search(r'Coherence:\s*([\d\.]+)', reply).group(1))
                cs = float(re.search(r'Consistency:\s*([\d\.]+)', reply).group(1))
                
                print(f"  [{topic_name}] CR={cr:.2f} FA={fa:.2f} AC={ac:.2f} CO={co:.2f} CS={cs:.2f}")
                results.append((cr, fa, ac, co, cs))
                break
            except Exception as e:
                retries -= 1
                if retries == 0:
                    print(f"  [{topic_name}] ERROR: {e}")
                time.sleep(2)
        
        time.sleep(1)
    except Exception as e:
        print(f"  [{topic}] SKIP: {e}")

# =====================================================================
# Bước 4: Tính trung bình
# =====================================================================
if results:
    avg = [sum(x)/len(results) for x in zip(*results)]
    print(f"\n{'='*70}")
    print(f"PROPOSED (EKRE + Self-Eval) — Average over {len(results)} best curricula:")
    print(f"  Context Relevance: {avg[0]:.2f}")
    print(f"  Faithfulness:      {avg[1]:.2f}")
    print(f"  Answer Correctness:{avg[2]:.2f}")
    print(f"  Coherence:         {avg[3]:.2f}")
    print(f"  Consistency:       {avg[4]:.2f}")
    print(f"{'='*70}")

# =====================================================================
# Bước 5: Chấm Baseline ZeroShot + NaiveRAG
# =====================================================================
baseline_prompt = """You are an expert evaluator for AI-generated educational textbooks.
You are evaluating a curriculum outline on "{topic}".

Score from 0.0 to 1.0 for each metric:
1. Context Relevance: Is the content focused on the topic?
2. Faithfulness: Is the factual content accurate?
3. Answer Correctness: Is the curriculum structure appropriate?
4. Coherence: Is the logical flow well-structured?
5. Consistency: Is the depth and tone consistent?

CONTENT:
{text}

Return ONLY:
Context Relevance: X.XX
Faithfulness: X.XX
Answer Correctness: X.XX
Coherence: X.XX
Consistency: X.XX"""

def eval_baseline_folder(folder, label):
    files = glob.glob(os.path.join(folder, '*.txt'))
    res = []
    print(f"\n--- Evaluating {label} ({len(files)} files) ---")
    for f in files:
        try:
            topic = os.path.basename(f).replace('.txt','')
            content = open(f, 'r', encoding='utf-8').read()
            if len(content) < 100: continue
            
            prompt = baseline_prompt.format(topic=topic, text=content[:6000])
            response = model.generate_content(prompt, generation_config=genai.types.GenerationConfig(temperature=0.0))
            reply = response.text
            
            cr = float(re.search(r'Context Relevance:\s*([\d\.]+)', reply).group(1))
            fa = float(re.search(r'Faithfulness:\s*([\d\.]+)', reply).group(1))
            ac = float(re.search(r'Answer Correctness:\s*([\d\.]+)', reply).group(1))
            co = float(re.search(r'Coherence:\s*([\d\.]+)', reply).group(1))
            cs = float(re.search(r'Consistency:\s*([\d\.]+)', reply).group(1))
            
            print(f"  [{topic}] CR={cr:.2f} FA={fa:.2f} AC={ac:.2f} CO={co:.2f} CS={cs:.2f}")
            res.append((cr, fa, ac, co, cs))
        except Exception as e:
            print(f"  [{topic}] ERROR: {e}")
        time.sleep(1)
    
    if res:
        avg = [sum(x)/len(res) for x in zip(*res)]
        return avg
    return None

score_zs = eval_baseline_folder(r"d:\tu_dong_giao_trinh\ThucNghiem_KetQua\Baseline_ZeroShot", "Zero-shot LLM")
score_rag = eval_baseline_folder(r"d:\tu_dong_giao_trinh\ThucNghiem_KetQua\Baseline_NaiveRAG", "Naive RAG")

# =====================================================================
# Bước 6: In bảng so sánh cuối cùng
# =====================================================================
print(f"\n{'='*90}")
print("BANG SO SANH CUOI CUNG (LLM-as-a-Judge / RAGAS)")
print(f"{'='*90}")
print(f"| {'Method':<33} | {'CR':>5} | {'FA':>5} | {'AC':>5} | {'CO':>5} | {'CS':>5} |")
print(f"|{'-'*34}|{'-'*7}|{'-'*7}|{'-'*7}|{'-'*7}|{'-'*7}|")
if score_zs:
    print(f"| {'Zero-shot LLM':<33} | {score_zs[0]:5.2f} | {score_zs[1]:5.2f} | {score_zs[2]:5.2f} | {score_zs[3]:5.2f} | {score_zs[4]:5.2f} |")
if score_rag:
    print(f"| {'Naive RAG':<33} | {score_rag[0]:5.2f} | {score_rag[1]:5.2f} | {score_rag[2]:5.2f} | {score_rag[3]:5.2f} | {score_rag[4]:5.2f} |")
if results:
    avg_p = [sum(x)/len(results) for x in zip(*results)]
    print(f"| {'**Proposed (EKRE + Self-Eval)**':<33} | {avg_p[0]:5.2f} | {avg_p[1]:5.2f} | {avg_p[2]:5.2f} | {avg_p[3]:5.2f} | {avg_p[4]:5.2f} |")
print(f"{'='*90}")
